import "./globals.css";
import type { Metadata } from "next";
import { Nunito, Nunito_Sans} from 'next/font/google'
import clsx from "clsx";
import { createClient } from "@/prismicio";

const nunito = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito',
  display: 'swap'
})

const nunitoSans = Nunito({
  subsets: ['latin'],
  variable: '--font-nunito-sans',
  display: 'swap'
})

export async function generateMetadata(): Promise<Metadata> {
 const client = createClient()

 const page = await client.getSingle("settings")

  return {
    title: page.data.site_title || "Flowrise",
    description: page.data.meta_description || "Flowrise is the relaxing app for you.",
    openGraph: {
      images: [page.data.og_image.url || ""],
    },
  }
}


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(nunito.variable, nunitoSans.variable)}>
      <body>
        <header>HEADER!</header>
        {children}
        <footer>FOOTER!</footer>
      </body>
    </html>
  );
}
